### ISSUE TITLE
Список нейронов

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#1]
Для модели из 15 нейронов в скрытом слое получить отсортированный список нейронов.

### Описание

У каждого нейрона есть 784 весовых коэффициентов плюс смещение. Эвклидова норма (сумма квардратов) коэффициентов будем называть *мощностью* нейрона.
Мы можем отсортировать нейроны по мощности всех его коэффициентов.

Также у каждого нейрона есть "выходные" веса. Эти веса доступны через выходной слой. Необходимо тоже считать их мощность, т.е. получить *выходную* мощность нейрона. Она может нам помочь при подготовке алгоритма по устранению "слабых" нейронов.

### Результат

Вывести список мощностей нейронов. Выяснить наибольшую и наименьшую мощьность. Построить график, чтобы видеть примерное распределение мощности.
Также напротив мощности каждого нейрона вывести соответствующую выходную мощность.

**Comment by helenross636** [comment]
Нашла мощность для малой сети. Хотела уточнить по поводу выходной мощности. На выходном слое меньше "ветвей" (по 10, а не по 784 как в скрытом). Все равно посчитать так же мощность (квадратами)?

![image](https://user-images.githubusercontent.com/47567451/161400051-5d22a441-3280-4699-9e1d-3c2f826e981a.png)

**Comment by igsha** [comment]
Да, посчитать квадратами выходную мощность. Только сортировать надо `layer1` массив, а не `weight_origin`. Нужно также посмотреть смещения, они хранятся отдельно.

**Comment by helenross636** [comment]
Переделала расчет мощностей и выходных мощностей. Не уверена, где смещение хранится, может в model.layers[0].get_weights()[1]?

**Comment by igsha** [comment]
> Переделала расчет мощностей и выходных мощностей. Не уверена, где смещение хранится, может в model.layers[0].get_weights()[1]?

Выведите форму этого массива и посмотрите, где хранится массив из одного числа - это и есть смещение. Смещение для каждого нейрона всегда одно число. Но они могут быть соединены для всех нейронов, поэтому есть смысл ещё поискать массив из 15 элементов.

**Comment by helenross636** [comment]
Убрала сортировку, нашла смещение для скрытого слова
![image](https://user-images.githubusercontent.com/47567451/163713910-45808201-0d96-4844-8f7b-58d5113c9cd5.png)
