### ISSUE TITLE
Изучение устойчивости

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#11]
# Мотивация

Насколько меняются характеристики сети при принудительном размножении нейронов.

# Реализация

* Взять сеть с 30-ю нейронами
* Каждый нейрон размножить 50 раз (получить искусственную сеть из 1500 нейронов)
* Выходные веса каждого нейрона поделить на 50
* Запустить сеть на тестовых данных (evaluate) и распечатать результаты
* Запустить 30-и нейронную сеть на тех же тестовых данных и распечатать результаты
* Сравнить результаты

**Comment by helenross636** [comment]
Есть какая-то специальная функция, для копирования/дублирования нейронов?

**Comment by igsha** [comment]
Вы гуглили? Я не в курсе, есть/нет такой функции. Можно просто создать сеть большего размера и использовать метод `set_weights`, чтобы задать значения весов нейронов.

**Comment by helenross636** [comment]
А, поняла. Создать новую сеть, а не добавлять в старую. Да, гуглить пыталась, но даются ссылки на копирование биологического мозга.

**Comment by helenross636** [comment]
Вроде сделала все правильно, но результат прям очень плохой:
https://github.com/helenross636/magic_season/blob/main/%23Task_11.ipynb

**Comment by igsha** [comment]
> model_50.layers[2].set_weights([w50T, np.ones(model_50.layers[2].get_weights()[1].shape)])

У Вас смещения все равны 1. Нужно тоже скопировать от предыдущей сети. Смещения тоже нужно на 50 поделить.

А где копирование соответствующих входных весов для нейронов? Сейчас там мусор. Должно быть `model_50.layers[1].set_weights(...)`, причём делить их на 50 не нужно.

**Comment by helenross636** [comment]
Смещение я раньше находила через `get_weights()[1]`, а у `kernel` вообще нет параметров.

**Comment by igsha** [comment]
> Смещение я раньше находила через `get_weights()[1]`, а у `kernel` вообще нет параметров.

Потому что есть есть отдельное поле для смещений `model.layers[2].bias`. Больше углите, внимательнее читайте документацию.

**Comment by helenross636** [comment]
Да, как раз нашла это. Только получается, что до этого задавались веса входного слоя все таки? Потому что выходной (10,30). Сейчас пробую по такой логике все параметры задать. И делить на 50 буду выходные веса, которые соответствуют слою (10,30), получается.

**Comment by helenross636** [comment]
Получилось, что точность увеличилась на 0.05%
https://github.com/helenross636/magic_season/blob/main/%23Task_11.ipynb

**Comment by igsha** [comment]
`b50_2` не нужно делить на 50, так как мы делили веса. Было $w\cdot x + b$, стало $\frac{W}{50}\cdot x + b$. Веса в среднем не изменились, поэтому корректировка матожидания не нужна. Прогоните, посмотрите на результат.

**Comment by helenross636** [comment]
Тогда точность повышается на 0.26%
https://github.com/helenross636/magic_season/blob/main/%23Task_11.ipynb

**Comment by helenross636** [comment]
> Тогда точность повышается на 0.26%
> https://github.com/helenross636/magic_season/blob/main/%23Task_11.ipynb

Нет, точность не изменилась. Не знаю, почему, но при повторном обучении исходных моделей, точность первой стала 96,97%. Точности остальных моделей также немного изменились, хотя код запускался один и тот же. 

В итоге, точность размноженной не изменилась совсем.

**Comment by igsha** [comment]
Походу вы не задали `seed`, чтобы была повторяемость результатов. В данном задании требовалось как раз доказать, что точность не меняется при добавлении избыточности. Сохраните полученную сеть на всякий случай под каким-нибудь особы именем. Это пойдёт в диссертацию, где-нибудь в начале 2-й главы.
