### ISSUE TITLE
Написание текста диссертации

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#12]
# Мотивация

Закончить обучение в магистратуре.

# Реализация

* Получение плана диссертации с обозначениями разделов
* Описание обзора существующих методов
* Описание исследований
* Описание результатов исследований
* Заключения

**Comment by helenross636** [comment]
•	Аннотация 
•	Оглавление
•	Введение
•	Глава 1. Подготовка к исследованию.
  o	Нейронные сети
  o	Функции активации
  o	Прунинг нейронных сетей
  o	Среда разработки
•	Глава 2. Исследование.
  o	Обзор базы данных
  o	Модель нейронной сети
  o	Построение и обучение нейронных сетей
  o	Анализ результатов обучения
    	Точность, время, затраты
    	Точные и приблизительные нули
    	Мощность нейронов
    	Дисперсия и среднее
    	Ковариация
    	Поиск копий нейронов
  o	Устранение избыточных нейронов
•	Глава 3. Результаты исследования.
•	Заключение
•	Список литературы

**Comment by helenross636** [comment]
Обновленное оглавление:

АННОТАЦИЯ	2
ВВЕДЕНИЕ	4
ГЛАВА 1. ПОДГОТОВКА К ИССЛЕДОВАНИЮ.	5
1.1 Нейронные сети.	5
1.2. Функции активации	7
1.3. Оптимизаторы	13
1.4. Прунинг нейронных сетей.	21
ГЛАВА 2. ИССЛЕДОВАНИЕ.	27
2.2. Библиотека Keras.	27
2.3. База данных MNIST	27
2.4. Создание нейронных сетей.	28
2.5. Анализ результатов обучения.	34
2.5.1. Изучение устойчивости нейронной сети.	34
2.5.2. Точные и приблизительные нули.	34
2.5.3. Мощность нейронов.	36
2.5.4. Среднее и дисперсия.	37
2.5.5. Ковариация входа скрытого слоя.	38
2.5.6. Корреляция выхода скрытого слоя.	39
2.6. Поиск похожих нейронов.	41
2.7. Устранение избыточных нейронов.	41
2.7.1. Первый подход.	41
2.7.2. Второй подход.	42
ГЛАВА 3. РЕЗУЛЬТАТЫ ИССЛЕДОВАНИЯ.	44
ЗАКЛЮЧЕНИЕ	45
СПИСОК ЛИТЕРАТУРЫ	46

Не совсем понимаю, что надо писать в аннотации.

**Comment by igsha** [comment]
Ничего не надо писать в аннотации. Её обычно пишут к статьям, а не к диссертациям.

**Comment by helenross636** [comment]
Просто в бакалавриате ее писали.

**Comment by igsha** [comment]
2.5.2. Точные и приблизительные нули. 34
2.5.3. Мощность нейронов. 36
2.5.4. Среднее и дисперсия. 37

Эти разделы не нужны, так как они нам не помогли. Опишите только корелляционную матрицу. Нужно показать связь между разделом 2.5.1.

**Comment by igsha** [comment]
2.5. Анализ результатов обучения. 34 => переименовать в "Поиск похожих нейронов"

**Comment by igsha** [comment]
2.3. База данных MNIST 27 => переименовать в "Описание исследуемой базы данных" и поставить первым разделом в главе

**Comment by helenross636** [comment]
> ... Опишите только корелляционную матрицу. Нужно показать связь между разделом 2.5.1.

Устойчивость я проверяла на наименьшей модели, а корреляцию - на остальных в основном смотрела. 
Сказать, что аналогичной устойчивостью обладают все модели, а для изучения их совместной связи, была рассмотрена корреляция?

**Comment by helenross636** [comment]
А если я сюда добавлю файл, он потом не всплывет при проверке на антиплагиат?

**Comment by igsha** [comment]
залейте файл в гуглодоксы. Можно даже PDF-файл. Я там откомментирую. Вы же так делали с презентацией.
Антиплагиат берёт проверенные источники. Гитхаб не относится к публикуемым статьям.

**Comment by helenross636** [comment]
https://docs.google.com/file/d/1uqh2ZM57BIf7L52tTziuUvMPlfA5__M3/edit?usp=docslist_api&filetype=msword

**Comment by igsha** [comment]
Написал замечания.

**Comment by igsha** [comment]
Выяснил про минимум 50 страниц. Приложение тогда не нужно вставлять. Исправляйте замечания. Потом снова мне пришлите через гугл-доки, но только pdf-файл. Я посмотрю и, если не будет больше замечаний, отправим дальше на кафедру. Только не затягивайте. И не суетитесь. Если что, я могу ещё попридержать сроки до завтра на кафедре.

**Comment by helenross636** [comment]
> Выяснил про минимум 50 страниц. Приложение тогда не нужно вставлять. 

Я вроде читала, что приложения идут после оглавления и не считаются, как страницы. А еще надо будет в ориокс заливать все материалы. Я могу туда сохранить файлы с кодами потом. Либо добавить одно приложение с указанием ссылки на репозиторий.

**Comment by igsha** [comment]
> Приложение тогда не нужно вставлять

Я же написал, что не нужно приложения.

**Comment by helenross636** [comment]
Обработала замечания. Вот pdf файл

https://drive.google.com/file/d/1790CnHzvGm3qGwrG6cHPmi06EQWU4hEx/view?usp=sharing

**Comment by igsha** [comment]
Посмотрите мои комментарии и поправьте.

**Comment by helenross636** [comment]
Поправила.

**Comment by igsha** [comment]
Отсылайте на кафедру. Переключайтесь на презентацию.
