### ISSUE TITLE
Презнетация для защиты

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#13]
Необходимо продолжить работу над презентацией для предзащиты.

* Добавить описание прореживание нейронов модели
* Соединить хирургию мозга с описанием способа устранения избыточных нейронов

**Comment by helenross636** [comment]
Первый пункт - это описания именно применяемого способа?
Второй пункт - соединить хирургию именно биологического мозга с прореживанием нейронных сетей?

**Comment by igsha** [comment]
Да, применяемый способ. Нужно показать, что мы прореживаем не связи нейронов, а сами нейроны.

Оптимальная хирургия мозга - это про нейронные сети. Там никакой биологический мозг не режут. У вас же в презентации способы написаны. Мы используем способ прореживания.

**Comment by helenross636** [comment]
Обновила презентацию. Надо только последний слайд с заключением добавить.

**Comment by igsha** [comment]
Где ссылка?

**Comment by helenross636** [comment]
https://docs.google.com/file/d/1oCCg1Waoll7gOtm0RjjKdg1LGH-PEtuT/edit?usp=docslist_api&filetype=mspresentation
