### ISSUE TITLE
Корелляция выходных весов

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#14]
# Мотивация

Определени корелляции выходных весов.

# Реализация

Построить матрицу корелляции (в примере я приблизил первые 100 элементов):
```python
w2 = model.layers[2].kernel
lala = np.abs(np.corrcoef(w2))
np.fill_diagonal(lala, 0)
plt.imshow(lala[:100, :100], cmap='hot')
plt.colorbar()
```

Вывести сколько весов будут с высокой корелляцией для каждой модели:
```python
nn = [i for i, a in enumerate(lala) if np.sum(a > 0.9) != 0]
print(len(nn))
```

**Comment by helenross636** [comment]
Готово:
https://github.com/helenross636/magic_season/blob/main/%23Task14.ipynb

**Comment by igsha** [comment]
Я что-то не понимаю, почему у модели в 30 нейронов корелляционная матрица оказалась размерностью больше 300? Она должна быть 30x30. Попечатайте в цикле размерность `w2.shape`.

**Comment by helenross636** [comment]
При копировании кода не добавила транспонирование. Поэтому и под маску так много попало. 
https://github.com/helenross636/magic_season/blob/main/%23Task14.ipynb

**Comment by igsha** [comment]
Нужны выходные веса. Это означает, что веса должны иметь последнюю размерность 10. У Вас сейчас 784.

**Comment by helenross636** [comment]
Выходные. Да, увидела. 
https://github.com/helenross636/magic_season/blob/main/%23Task14.ipynb

**Comment by igsha** [comment]
Нужно сравниться только с 0.9. Остальные не важны, так как на 0.9 и так много похожих нейронов.
Создам задачу для ещё одного подхода редукции сети.
