### ISSUE TITLE
Корелляция весов разных моделей

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#15]
# Мотивация

Выяснение насколько похожи веса разных моделей.

# Реализация

Взять две разные модели (1500 и 5000). Получить веса из `model.layers[2].kernel` и сконкатенировать в одну матрицу A. Матрица должна быть размера 6500x10. Показать матрицу на картинке.

Получить те элементы матрицы `A[0:5000]` (модель 5000), которые соответствуют элементам `A[5000:]` (модель 1500) по метрике корелляции больше 0.9.

**Comment by helenross636** [comment]
Не уверена, что верно поняла вторую часть задания, но сделала вот так:
https://github.com/helenross636/magic_season/blob/main/%23Task15.ipynb

**Comment by igsha** [comment]
Показать нужно быть корелляционную матрицу, а не матрицу полученных весов. Опечатка

**Comment by igsha** [comment]
Корелляцию нужно взять от всей полученной матрицы. Далее рассматриваем только подматрицу `A[1500:, 0:1500]`. Должна быть матрица размера 5000x1500. Вот теперь в этой матрице ищите те значения, которые больше 0.9

**Comment by helenross636** [comment]
Переделала:
https://github.com/helenross636/magic_season/blob/main/%23Task15.ipynb

**Comment by igsha** [comment]
Вот тут неправильно написано:
```python
for idx, k in enumerate(mask):
  nk = k.nonzero()[0]
  if len(nk) != 0:
    similar[idx] = nk[np.argmax(am[idx,nk])]
```
Ваши индексы `nk` принадлежат массиву `mask`, который соответсвует `am[1500:, :1500]`, а не `am`. Вам нужно сохранить новый `am2 = am[1500:, :1500]` и далее работать именно с ним, а не с `am`.

**Comment by helenross636** [comment]
Я, конечно, создала am2, но ведь это все равно одно и то же?
https://github.com/helenross636/magic_season/blob/main/%23Task15.ipynb

**Comment by igsha** [comment]
> Я, конечно, создала am2, но ведь это все равно одно и то же?

Нет, это не одно и то же. В первом случае Вы выбираете, скажем, 429-ую строку из матрицы `am`, а в другом случае 429-ую строку из матрицы `am2`, что соответствует индексу 429+1500 в матрице `am`.

**Comment by igsha** [comment]
Переделайте формирование словаря `similar`:
```python
from collections import defaultdict
....
similar = defaultdict(list)
for idx, k in ...:
    ...
    similar[nk[np.argmax(am2[idx, nk])]].append(idx)
```
В итоге мы будем иметь словарь, ключи которого представляют индекс нейрона из сети 1500, а значением является массив индексов нейронов из сети 5000. Задача потом будет состоять из замены всех нейронов в 5000-модели на один нейрон из 1500-модели.
