### ISSUE TITLE
Метод редукции с помощью пересадки нейронов

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#16]
# Мотивация

Пересадка мозга.

# Реализация

Будет 2 подхода:
1. Подход №1 "пересадка"
    1. Создать массив весов нейронов из 1500-модели, которые похожи на нейроны из 5000-модели (словарь `similar` см. #15). Полученные веса поделить на количество нейронов из 5000-модели (величина `len(similar[idx])`).
    2. Добрать нейроны из 5000-модели, которые нет в словаре `similar`
    3. Создать новую сеть и инициализировать её созданными весами
    4. Запустить тестирование новой сети (обучение не нужно), получить метрики качества
2. Подход №2 "полная редукция"
    1. Из предыдушего подхода делаются все пункты, кроме 2 (нейроны не добираются)
    2. Запустить тестирование и получить метрики качества

**Comment by helenross636** [comment]
Справедливо ли утверждение, что порядок нейронов в сети не важен? 
то есть , если соблюдать соответствие между входными и выходными весами, можно в новую сеть добавить сначала нейроны из 1500, а потом из 5000?

**Comment by igsha** [comment]
Порядок не важен. Можете в любом порядке добавлять.

**Comment by helenross636** [comment]
Первый подход оказался довольно успешным: точность 96.89%.
Второй подход провалился: точность 9.74%
(по аналогии с предыдущими задачами делила выходные веса нейронов.)
https://github.com/helenross636/magic_season/blob/main/%23Task15-16.ipynb

**Comment by igsha** [comment]
`new_out_k = new_out_k/count` - нужно каждый делить на `len(similar[idx])`. См. описание задачи + #11.

---

Непонятная процедура добавления. У меня есть подозрение, что некоторые веса остались нулевыми.
Сначал создайте массив уникальных индексов, которых нет в `similar` в качестве значений:
```py
u = {x for v in similar.values() for x in v}
nu = set(range(5000)) - u
```
Далее выбирайте только те веса, которые есть в нужных массивах [^1]:
```py
wi = model1500.layers[2].kernel.numpy()[:, list(similar.keys())]
wi2 = model5000.layers[2].kernel.numpy()[:, list(nu)]
bi = model1500.layers[2].bias.numpy()[list(similar.keys())]
bi2 = model5000.layers[2].bias.numpy()[list(nu)]
```
Помните, что выходные веса имеют другую направленнойсть:
```py
wo = model1500.layers[3].kernel.numpy()[list(similar.keys())]
wo2 = model5000.layers[3].kernel.numpy()[list(nu)]
```
На всех шагах печатайте размерности полученных матриц.

Затем просто конкатенируйте матрицы в нужном направлении:
```py
in_w = np.hstack((wi, wi2))
in_b = np.concatenate((bi, bi2))
out_w = np.vstack((wo, wo2))
```

При делении Вам нужно получить матрицу, совпадающую по размеру с `wo`. Получение длин делается так:
```py
count = np.asarray([len(x) for x in similar.values()])
count = count[..., np.newaxis]
count = np.repeat(count, 10, axis=1)
```
В первой строке получаем массив из длин, во второй строке расширяем массив в матрицу, в третьей строке делаем матрицу размера Nx1 в Nx10. После этого размерности матриц `count` и создаваемой `wo` сходятся, и их можно делить:
```py
wo = model1500.layers[3].kernel.numpy()[list(similar.keys())] / count
```

[^1]: `list(similar.keys())` и `list(nu)` можно, конечно же, заранее сохранить под новыми переменными.

**Comment by helenross636** [comment]
Переделала. 
У первого подхода точность стала как у моделей 5000 и 1000: 98.10%
(при этом выходное смещение взяла от сети 1500; а если брать от 5000, то получается 98.09%)

У второго подхода точность 97.64%. 

https://github.com/helenross636/magic_season/blob/main/%23Task15-16.ipynb

**Comment by igsha** [comment]
> при этом выходное смещение взяла от сети 1500

Там нужно что-то придумать, наподобие взвешенной суммы от количества нейронов из 1500 модели и 5000. На это не хватит времени, поэтому забьём.

В остальном результаты получены хорошие.
