### ISSUE TITLE
Метод редукции сети с помощью удаления нейронов

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#17]
# Мотивация

Удаление предположительно похожих нейронов.

# Реализация

1. В качестве эксперимента возбмите 5000-модель
1. Длеается на основе #14 
1. Подготовить словарь `similar` как в задаче #16 
1. Создавать словарь `similar` так, чтобы ключом был индекс, а значением был массив тех нейронов, которые имеют максимальную корелляцию с ним (см. #16)
1. Выявить дубликаты в словаре: нейрон присутсвует как в ключе, так и в одном из массивов
1. Удалить дубликаты: побеждает тот нейрон, у которого в списке больше похожих на него кандидатов: `len(similar[idx0])) > len(similar[idx1]))`

Далее следует 2 подхода редукции:
1. Спартанский подход: оставляем только "сильнейших":
    1. Отобрать только те нейроны, которые остались в качестве ключей в `similar`
    1. Выходные веса полученных нейронов умножить на количество похожих на них нейронов
    1. Создать новую сеть на осонове полученных нейронов
    1. Запустить тесты, получить результатирующие метрики
1. Гуманный подход:
    1. Проделать пункты 1-2 из предыдущего подхода
    2. Добавить оставшиеся нейроны из модели, которых нет в `similar` ни в качестве ключей, ни в качестве значений
    3. Проделать пункты 3-4 из предыдущего подхода

**Comment by helenross636** [comment]
Можно уточнить?

1. Ранее строилась маска по матрице коэф корелляции > 0.9 (например). Потом начиналость рассмотрение каждой строки. Если в ней находились элементы с меткой `True`, то среди них искалось наибольшее значение в исходной матрице. И по индексу столбца `(nk)` исходной матрицы определялся ключ, в который записывался каждый индекс строки`(idx)`. В итоге, ключами становятся только наибольшие индексы столбцов `(nk[np.argmax(am[idx, nk])]`), а словами - все индексы строк `(idx)`. 

2. А сейчас надо находить максимальное значение по столбцу и записывать его в ключ по номеру строки? Тогда:

2.1. может ли такое быть, что длина словаря `len(similar)<5000`?
2.2. если нет, то каждому ключу будет соответствовать только одно значение, и сравнение количества значений в дубликатах не будет иметь смысла.

**Comment by igsha** [comment]
`nk[np.argmax(am[idx, nk])]` - это ключ, а значением будет массив. `len(similar)` всегда будет меньше 5000. Есть какие-то конкретные ошибки?

**Comment by helenross636** [comment]
Я просто пыталась понять разницу между словарями из 16 и 17. Если я просто транспонирую исходную матрицу или словарь, будет не то, что надо?

**Comment by igsha** [comment]
Я же ссылку дал на другую задачу, потому что словари одинаково строятся.

**Comment by helenross636** [comment]
Вроде получилось. 
Спартанский: 94.14%
Гуманный: 97.37%

https://github.com/helenross636/magic_season/blob/main/%23Task17.ipynb

**Comment by igsha** [comment]
Эти два подхода попробуйте на 1500-модели и 10000. Составьте таблицу: какие проценты были, какие стали.

**Comment by helenross636** [comment]
Как создавать словарь `similar` для 1500 и 10000? Сейчас брала из конкатенации 1,5к и 5к.

**Comment by igsha** [comment]
> Как создавать словарь `similar` для 1500 и 10000? Сейчас брала из конкатенации 1,5к и 5к.

Это не тот метод. Почитайте описание. Вам нужен только 1.5к модель либо только 10к модель. Конкатенировали мы в другой задаче. Её мы уже поисследовали.

**Comment by helenross636** [comment]
Просто в самом начале задачи написано было "Подготовить словарь similar как в задаче #16" и потом "потому что словари одинаково строятся". А в 16 задаче строили именно через конкатенацию.

В любом случае, я для всех моделей (1.5к, 5к и 10к) построила новые словари на основе только их корреляционных матриц и выполнила дня них оба подхода:
https://github.com/helenross636/magic_season/blob/main/%23Task17.ipynb

Получились следующие результаты:
![image](https://user-images.githubusercontent.com/47567451/173793393-7be77bb9-fcde-48f0-97e2-ed211c3476ab.png)

**Comment by igsha** [comment]
А сколько нейронов осталось в каждом из подходов? И сколько была точность у оригинальных моделей?

**Comment by helenross636** [comment]
Первая таблица не совсем верная, вот так будет правильней.

![image](https://user-images.githubusercontent.com/47567451/173805698-1f5dc61b-c89f-49ad-af76-d42fb5980d52.png)

**Comment by igsha** [comment]
Хорошо. Оформляйте результаты всё в диссертации.
