### ISSUE TITLE
Сравнение мощностей

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#2]
После работы над #1 проделать поиск мощностей нейронов скрытого слоя для модели из 1500 нейронов и 5000 нейронов.

### Результат

* Сравнить максимальные/минимальные мощности (входные и выходные) для всех моделей.
* Сравнить графики распределения мощностей, чтобы понять, влияет ли количество нейронов скрытого слоя на распределение мощности.

**Comment by helenross636** [comment]
Добавлен новый коммит для сетей 1500 и 5000 нейронов.

**Comment by igsha** [comment]
Сейчас результаты неверные, потому что сортируются веса, а не мощности. После сортировки мы не знаем, какому нейрону принадлежат веса. Необходимо вообще убрать сортировку.

**Comment by helenross636** [comment]
![image](https://user-images.githubusercontent.com/47567451/163710271-fe8903a1-95b8-43d7-bc7a-2ee5301ded00.png)

**Comment by helenross636** [comment]
>1500 нейронов
 ![image](https://user-images.githubusercontent.com/47567451/163710271-fe8903a1-95b8-43d7-bc7a-2ee5301ded00.png)
5000 нейронов
![image](https://user-images.githubusercontent.com/47567451/163710329-a36b5073-df97-450c-a896-3c18971fee39.png)
