### ISSUE TITLE
Исследование выходной мощности нейронов

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#4]
Взять выходные связи нейронов скрытого слоя и построить средние значения и дисперсии. Нас будут интересовать нейроны с самой маленькой дисперсией. Как обычно привести результаты для модели с 15, 1500 и 5000 нейронов.

**Comment by igsha** [comment]
@helenross636, я жду результатов.

**Comment by helenross636** [comment]
Имеется в виду находить среднее и дисперсию для каждого нейрона отдельно? Иначе у меня только 3 пары чисел будет в итоге, по паре для каждой сети.

**Comment by helenross636** [comment]
![image](https://user-images.githubusercontent.com/47567451/165329783-1ba7717c-44fa-4d0d-b239-62622e7440ea.png)

![image](https://user-images.githubusercontent.com/47567451/165310802-70faaaf2-e9be-4529-8828-a845fbe141f6.png)

![image](https://user-images.githubusercontent.com/47567451/165310884-ec5402b3-91c8-4990-9529-516ee13defc7.png)

**Comment by igsha** [comment]
Средних и дисперсий должно быть по количеству нейронов в скрытом слое, а не 10 штук.

**Comment by helenross636** [comment]
15 нейронов:
![image](https://user-images.githubusercontent.com/47567451/165494299-04dbda08-de87-42a8-9b36-1a2c658852be.png)
1500 нейронов:
![image](https://user-images.githubusercontent.com/47567451/165494415-308278fc-eaeb-4532-8074-b0988872c988.png)
5000 нейронов:
![image](https://user-images.githubusercontent.com/47567451/165494508-7bb081ea-5953-4952-98cc-9312e161c63e.png)

**Comment by igsha** [comment]
Дисперсия у всех нейроной подозрительно одинаковая. Походу дела опять не то сделали. Насоздам задач, потом снова к этой вернёмся.

**Comment by igsha** [comment]
После #5 вернётесь снова к этой задаче. Сейчас у Вас зачем-то считается среднее и дисперсия входной мощности нейронов, а не выходной. Плюс для модели в 15 нейронов Вы делите дисперсию на 10, а не на 784. Используйте `np.mean` и `np.std`, чтобы не писать один и тот же код и не вводить больше ошибок.

**Comment by helenross636** [comment]
Я же первый раз посчитала значения для выходного слоя, что я думала, считается выходными весами для скрытого.

**Comment by igsha** [comment]
В первый раз была посчитана входная мощность выходного слоя. Во второй раз Вы посчитали входную мощность скрытого слоя. Я прошу посчитать **выходную** мощность скрытого слоя. Посмотрите, как Вы делали это раньше. Код сохранён в репозитории.

**Comment by helenross636** [comment]
Я считала входные мощности скрытого и выходного слоя.

**Comment by igsha** [comment]
> Я считала входные мощности скрытого и выходного слоя.

Да, но это нам не нужно. Нужна выходная мощность скрытого слоя. Она не то же самое, что входная мощность выходного слоя.
Должно быть:
* Количество элементов в векторах среднего и дисперсии совпадать с количеством нейронов в скрытом слое
* Вычисление средних и дисперсий должно вести при усреднии по 10 (а не по 784)

**Comment by igsha** [comment]
@helenross636, я жду.

**Comment by helenross636** [comment]
Раньше мы говорили, что обозначенные на рисунке веса являются выходными для скрытого слоя и входными для выходного? Или я неправильно поняла? 
 
Как усреднение может вестись по 10, если количество нейронов на скрытых слоях никогда не 10?
 ![image](https://user-images.githubusercontent.com/47567451/166923492-1aedc371-40b8-495b-bd88-c46ebe142397.jpg)

**Comment by igsha** [comment]
Усреднение ведётся по весам, а не по нейронам. Посмотрите, как Вы вычисляли выходную мощность в https://github.com/helenross636/magic_season/blob/main/%22mnist_keras_ipynb%22.ipynb:
```python
weight_origin2=model.layers[1].get_weights()[0].flatten()
...
for i in range(15):
  sum2 = 0
  for j in range(10):
    sum2 = sum2 + weight_origin2[i*10 + j]*weight_origin2[i*10 + j]
  layer2[i] = sum2
```

**Comment by helenross636** [comment]
Разобралась в своей ошибке понимания. Добавила новый коммит, там для всех четырех нейронных сетей построеные выходные средние и дисперсии скрытых слоев.

**Comment by igsha** [comment]
* Сделайте всё через цикл, чтобы не было повторяющихся частей кода. Это обезопасит от ошибок.
* Уберите про корень дисперсии. Это и есть настоящая дисперсия, а `disp*disp` - это квадрат дисперсии, он не особо интересен, поэтому его не нужно приводить
* Сравнение матожидания с порогами не нужны

**Comment by helenross636** [comment]
Сделать в циклах одинаковые вычисления и построения для разных моделей, то есть перемешать их?

**Comment by igsha** [comment]
Как написано в задании #5

**Comment by helenross636** [comment]
Сделала.
https://github.com/helenross636/magic_season/blob/main/Load_nets%2Bwork_%234.ipynb
