### ISSUE TITLE
Загрузка и сохранение моделей

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#5]
Почитать статью https://www.tensorflow.org/guide/keras/save_and_serialize.

1. Обучение всех моделей выделить в отдельный ipynb файл. В конце файла сохранять модели с помощью `model.save()` в формате `h5`.
1. Добавить модель на 10000 нейронов. Итого будут модели на 15, 1500, 5000 и 10000 нейронов в скрытом слое.
1. Запустить скрипт, который в конце локально сохранит модели.
1. Загрузить модели куда-нибудь в облако, где они не потеряются. Либо поправить скрипт, чтобы он сразу мог сохранять в облако.

После проделанных действий создать ещё один файл, в котором будут загружаться модели и проводиться с ними исследования. Примерный код:
```python
for model_path in ["/path/to/model15.h5", "/path/to/model1500.h5", ...]:
    m = keras.models.load_model("my_model")
    weights = m.layers[1].get_weights()[0]
    aver = np.mean(weights, axis=1)
    dev = np.std(weights, axis=1)

    _, ax = plt.subplots()
    ax.plot(aver)
    ax.fill_between(range(len(aver)), aver - dev / 2, aver + dev / 2, alpha=0.25)
```

Таким образом не придётся каждый раз 2 часа ждать результатов. Такой подход также позволяет дообучивать сеть, загруженную через `load_model`.

**Comment by helenross636** [comment]
Сохранила модели, которые потом получилось загрузить.

**Comment by igsha** [comment]
После `save_model` не нужно проверять `load_model` - на это же время тратится.

Подкорректируйте количество эпох у моделей, чтобы они показывали одинковую точность. Отличия можно только в первом знаке после запятой. Сейчас у одной модели 93% точность, у другой 97% - это очень большое различие. Чем больше сеть по размеру, тем количество эпох должно быть меньше.

**Comment by helenross636** [comment]
relu дает повышение точности. Модель с 1500 нейронами за 2 эпохи обучилась на 93.45% точности

**Comment by igsha** [comment]
Повысить точность для 15-нейронной сетки можно как-то с помощью повышения количества эпох? Скажем, взять 3000 эпох.

**Comment by helenross636** [comment]
Да, только так видимо и можно, начну обучать.

**Comment by helenross636** [comment]
Точность практически не выросла (с 93.45% до 93.73%). Дальше только число нейронов увеличивать.

**Comment by igsha** [comment]
Увеличьте количество нейронов тогда с 15 до 20 или до 30

**Comment by helenross636** [comment]
Обновила модели, получила почти одинаковую точность для всех сетей.

**Comment by igsha** [comment]
Хорошо
