### ISSUE TITLE
Гистограмма выходной мощности

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#6]
Дополнить задание #4 гистограммой.

* Гистограмма должна содержать 200 бинов
* Для надёжности, приведите график отсортированной выходной мощности, чтобы нам было видно на сколько частей следует разбивать гистограмму

**Comment by helenross636** [comment]
Последние 2 куска кода

**Comment by helenross636** [comment]
Последние 2 куска кода:
https://github.com/helenross636/magic_season/blob/main/Load_nets%2Bwork_%236.ipynb

**Comment by igsha** [comment]
Фиксируем выводы:
* Центр гистограммы дисперсии смещается от 0.06 до 0.045 (возможно это связано с количеством нейронов)
* Гистограммы среднего практически не отличаются
* Отсортированная кривая имеет угол наклона, который уменьшается при увеличении числа нейронов
