### ISSUE TITLE
Сравнение входных весов

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#7]
Задача: выявление одинаковых нейронов.

Для каждой модели из N нейронов в скрытом слое:

1. Сравнить входные веса кажого нейрона с каждым по метрике среднеквардратического отклонения
1. Каждое сравнение выдаёт число. Таким образом, каждый нейрон будем иметь N чисел. Всего будет произведено N<sup>2</sup> сравнений
1. Построить матрицу сравнений с помощью функций
    ```python
    plt.imshow(a, cmap='hot', interpolation='nearest')
    plt.colorbar()
    ```
1. Проверить, что по диагонали у матрицы нули

Вторая часть (делается после получения результатов):

1. Выявить те нейроны, которые будут иметь очень маленькие значения в матрице и не стоять на диагонали. Назовём такие нейроны копиями (их может не быть
1. Для нейронов-копий провести процедуру сравнений выходных весов. Необходимо понять, похоже они полностью или нет.

**Comment by helenross636** [comment]
"Каждое сравнение выдаёт число. Таким образом, каждый нейрон будем иметь N чисел. Всего будет произведено N2 сравнений" - какие числа должны выдавать сравнения для разных результатов (<>=)?

**Comment by igsha** [comment]
> 1. Сравнить входные веса кажого нейрона с каждым по метрике среднеквардратического отклонения

Среднеквадратическое отклонение - это число.

**Comment by helenross636** [comment]
Среднеквадратичное я могу найти как квадратный корень дисперсии (те np.std). Но эта функция принимает на вход массив чисел. А мне, если правильно поняла, надо каждый раз сравнивать только 2 числа? 
Значит ли это, что, например, для сети с 30 нейронами (по 10 выходных значений у каждого), надо сравнить все возможные пары значений среди 10 по формуле 
![image](https://user-images.githubusercontent.com/47567451/168424111-8dbe2ad0-c46f-4f3f-8cb3-1e1bc4a26e74.png)
Только в этом случае всего сравнений будет не N^2.

- Или надо сравнивать веса одного нейрона с весами другого
- или надо сравнивать веса в одном нейроне между собой?
![image](https://user-images.githubusercontent.com/47567451/168426111-8935ad4f-1306-44e1-886d-8f4f36a4bb47.png)
(те есть надо вести сравнения в пределах одного нейрона (по i) или между разными нейронами (по j)).

**Comment by igsha** [comment]
Каждый нейрон имеет на **входе** 784 значения (задание именно про входные веса). Сравнение по СКО (не важно, в квадрате или нет) между двумя нейронами - это сравнивать два вектора по 784 значения (просто вычесть их и взять функцию `np.std`). Получим **одно число**. Так проделать для всех возможных пар нейронов скрытого слоя (используются 2 вложенных цикла).

Примерный код:
```python
w = model.layers[1].get_weights()[0].transpose()
m = [[np.std(w0-w1) for w0 in w] for w1 in w]
plt.imshow(m, cmap='hot)
plt.colorbar()
```

Далее, где видны значения очень близкие к 0, изучаете их характеристики, как описано в задаче.

**Comment by helenross636** [comment]
Судя по графикам, копии можно увидеть только в сети с 30 нейронами. Но это наверное из-за масштаба сетки. Попробую посчитать через sum() количество значений, ниже определенной границы.
![584CD53F-DCE3-41B4-AE07-F3DC749786E5](https://user-images.githubusercontent.com/47567451/169225850-6b65538d-4596-49fb-8036-d3812536ace7.png)

**Comment by helenross636** [comment]
"Для нейронов-копий провести процедуру сравнений выходных весов. Необходимо понять, похоже они полностью или нет."  - например, по той же метрике среднеквадратичного? и как лучше отобразить результаты (графиком значений/гистограммой)?

**Comment by helenross636** [comment]
Построила гистограмму значений, потому что не была уверена в наличии копий. оказалось, их и нет.
https://github.com/helenross636/magic_season/blob/main/Load_nets%2Bwork_%237.ipynb

**Comment by igsha** [comment]
Так копий быть и не должно. Нужно выбирать быть маленькие отклонения.

**Comment by helenross636** [comment]
Я специально гистограммы строила, чтобы вообще значения посмотреть. У больших сетей они либо 0.06, либо 0.07. Не понятно, что считать маленьким отклонением

**Comment by igsha** [comment]
При построении гистрограммы нужно указывать количество бинов: `plt.hist(m[0], bins=1000)`. Ещё вы строите гистограмму только для первого нейрона. А что если похожи 20 и 500 нейроны?
0.06 означает, что мы можем все эти нейроны считать похожими. Сравните со значениями для 30-нейронной сеткой. Там значения в среднем около 0.27

**Comment by helenross636** [comment]
А, да, про построение только первого нейрона поняла ошибку. Просто мне кажется, что матрицы симметричны относительно главной диагонали, и я не хотела строить в 2 раза больше. В итоге построила в N раз меньше. 
«можем все нейроны считать похожими» - то есть копиями?

**Comment by igsha** [comment]
Попробуйте рассмотреть ковариацию, вместо `np.std`: https://numpy.org/doc/stable/reference/generated/numpy.cov.html или нормализованную версию https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html#numpy.corrcoef. Только внимательно изучите, что должно быть строками матрицы, а что столбцами на входе у `np.cov`. Каждая строка должна представлять веса одного нейрона. То есть матрица на входе должна иметь N строк по количеству нейронов и 784 столбца. Эту матрицу подаёте на вход `np.cov`. При анализе нужно отбросить единичные значения на диагоналях (для функции `corrcoef`).
Сюда покажите полученные ковариационные матрицы. И ещё используйте модели, натренированные через Adam.

**Comment by helenross636** [comment]
Даже не смотря на то, что при adam не получается получить примерно одинаковую точность?

**Comment by igsha** [comment]
> Даже не смотря на то, что при adam не получается получить примерно одинаковую точность?

Да. Сейчас нам нужно понять, как оценивать "одинаковость" нейронов.

**Comment by helenross636** [comment]
Натренированные модели (через adam):
https://github.com/helenross636/magic_season/blob/main/ALL_NETS.ipynb
30 нейронов: 96.46%
1500 нейронов: 96.93%
5000 нейронов: 96.90%
10000 нейронов: 96.48%
(переобучение что ли начинается?)
ковариация:
https://github.com/helenross636/magic_season/blob/main/Load_nets%2Bwork_%237.ipynb
![image](https://user-images.githubusercontent.com/47567451/170348905-0e7512f3-3cf7-4aea-9f95-7e32aea6fd71.png)
![image](https://user-images.githubusercontent.com/47567451/170348955-dd36179f-396e-4eb8-a218-425cda522dd0.png)
![image](https://user-images.githubusercontent.com/47567451/170348995-47754a8f-813a-40b2-8dc8-6c3c77182bda.png)
![image](https://user-images.githubusercontent.com/47567451/170349047-629860ea-2295-4669-a11f-35d0d2f089ca.png)

**Comment by igsha** [comment]
Что-то не так с выводом гистограмм для `np.cov`. Должен всегда во всех случаях присутствовать столбец на 1.0 с высотой равной количеству нейронов. Такой столбец присутсвует только для 30 нейронов (причём с натяжкой).

**Comment by helenross636** [comment]
Разве это не другой функции касалось?
"При анализе нужно отбросить единичные значения на диагоналях (для функции corrcoef)."

**Comment by igsha** [comment]
> Разве это не другой функции касалось? "При анализе нужно отбросить единичные значения на диагоналях (для функции corrcoef)."

 да, для `corrcoef`

**Comment by helenross636** [comment]
Вообще да, надо было наверное выпрямить матрицу перед построением гистограмм, а то они по нейронам строятся

**Comment by igsha** [comment]
А Вы точно те нейроный смотрите? Мне казалось, что нужно выбирать `model.layers[1]`, а не `model.layers[0]`.

**Comment by helenross636** [comment]
Да, поняла. Я смотрела вход, а не выход. меня спутала фраза "N строк по количеству нейронов и 784 столбца". 784 на входе

**Comment by igsha** [comment]
Размерность правильная. Мы должны вход смотреть. Но слой, кажется, не тот.

**Comment by helenross636** [comment]
model.layers[0] - это скрытый
model.layers[1] - это выходной (через него смотрели выход скрытого, транспонировав матрицу весов)

**Comment by igsha** [comment]
Поменяйте всё на `np.corrcoef`. Перед выводом изображения примените модуль и обнулите диагональ, распрямите матрицу перед построением гистограммы:
```python
m = np.abs(m)
np.fill_diagonal(m, 0)
plt.hist(m.flatten(), bins=1000)
```
Оформите данную задачу отдельным *.ipynb фалйом.

**Comment by helenross636** [comment]
Готово
https://github.com/helenross636/magic_season/blob/main/%23Task7.ipynb

**Comment by igsha** [comment]
При построении гистограммы используйте параметр `density=True`, чтобы масштаб был примерно одинаковым.

**Comment by igsha** [comment]
Вместо `model.layers[0].get_weights()[0]` используйте `model.layers[0].kernel`. Транспонировать веса можно через `np.transpose(model.layers[0].kernel)`, потому что это не numpy-массив, а ресурсный тензор.

**Comment by helenross636** [comment]
С последней версии моделей:
https://github.com/helenross636/magic_season/blob/main/%23Task7.ipynb
(смотрелись вторые слое, потому что теперь скрытые под этим номером)

**Comment by igsha** [comment]
Распечатайте `model.summary()`. Я не очень понимаю, сколько слоёв в модели. Очень похоже, что нужно ещё дообучить модели.

**Comment by helenross636** [comment]
Вот тут есть распечатка для всех моделей
https://github.com/helenross636/magic_season/blob/main/ALL_NETS_v2_0.ipynb

**Comment by igsha** [comment]
В общем, во входе нет никаких особненностей.
