### ISSUE TITLE
Подготовка презентации для предзащиты

### ISSUE THREAD

**Issue by igsha** [helenross636/magic_season#8]
Ориентировочный объём презентации 20 слайдов.
Разделы презентации:
* Актуальность исследования (1 слайд)
* Цель исследования (1 слайд)
* Обзор существующих методов отимальной хирургии мозга по теме диссертации (2-3 слайда)
* Общая схема системы исследования (1 слайд)
* Расписывание всех этапов из схемы
* Приведение графиков моделей (выводы: что похоже, что различается)
* Метод уменьшения количества нейронов в сети (пока так ещё и не добрались до этого)
* Влияние уменьшения количества нейронов на точность сети; требуется ли дообучение
* Выводы по диссертации

Презентацию выкладывать на гитхаб к коду либо ссылку сюда на онлай-документ (GoogleDocs). Формат можно использовать pptx.

**Comment by helenross636** [comment]
https://docs.google.com/presentation/d/1oCCg1Waoll7gOtm0RjjKdg1LGH-PEtuT/edit?usp=sharing&ouid=111342926171771753696&rtpof=true&sd=true

**Comment by igsha** [comment]
Необходимо дать доступ на комментарии и review.

**Comment by helenross636** [comment]
https://docs.google.com/presentation/d/1oCCg1Waoll7gOtm0RjjKdg1LGH-PEtuT/edit?usp=sharing&ouid=111342926171771753696&rtpof=true&sd=true

так можно комментировать. просто не хочу выкладывать ссылку на прямое редактирование в общий доступ, чтобы кто-то случайно не испортил.

**Comment by igsha** [comment]
* Добаваить номера слайдов
* Слайд №1: к.т.н., старший преподаватель
* Слайд №3: Цель исследования: удаление избыточных нейронов для уменьшения размера сети и увеличения производительности.
* Слайд №8: Нужно привести исследуемую архитектуру сети. Показать, какие данные на вход приходят, что на выходе, какие дополнительные слои есть, как функции активации используются.
* Слайд №10: Что это за графики? Заголовка "Анализ" недостаточно для описания графиков. Оси должны быть подписаны. Не нужно писать пороги. Нужно написать вывод, что хоть матожидание в 0, реальных нулей там нет.
* Слайд №11: Что это за графики? Оси нужно подписать.
* Слайд №12: Что это за графики? Это разве не то же самое, что на слайде №10?
* Слайд №13: Этот слайд лучше раскидать по предыдущим слайдам

**Comment by igsha** [comment]
> https://docs.google.com/presentation/d/1oCCg1Waoll7gOtm0RjjKdg1LGH-PEtuT/edit?usp=sharing&ouid=111342926171771753696&rtpof=true&sd=true
> 
> так можно комментировать. просто не хочу выкладывать ссылку на прямое редактирование в общий доступ, чтобы кто-то случайно не испортил.

Ок

**Comment by helenross636** [comment]
Сделала правки. 
По поводу одинаковых графиков: 13 слайд графики отсортированных значений, а 14 - гистограммы. Добавила оба тк разные выводы по ним можно сделать. 
Слайды 16-18 пока пустые.

**Comment by igsha** [comment]
Посмотрите мои комментарии к слайдам

**Comment by helenross636** [comment]
Проработала комментарии

**Comment by igsha** [comment]
Убавьте читаемый текст для слайдов 1-8. Остальные изменения уже будут для итоговой презентации.
